/**##############################################################
## MODULE: Classifier.h
## VERSION: 1.0 
## SINCE 2013-06-06
## AUTHOR Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au  
## DESCRIPTION: 
##     Inherited classifier, in order to get the weights  
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/



class Classifier: public drwnTMultiClassLogistic<drwnIdentityJointFeatureMap>
{
    public:
    vector< double > getWeights() {
        /*
        int nParameters = (*_weights).size();
        vector< double > tempWeights(nParameters);
        for (int i = 0 ; i < nParameters; i ++ ) {
            tempWeights[i] = (* _weights)[i];
        }*/
        return *_weights;

    }

};
