/**##############################################################
## MODULE: Classifier.h
## VERSION: 1.0 
## SINCE 2013-06-06
## AUTHOR Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au  
## DESCRIPTION: 
##     Inherited classifier, in order to get the weights  
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/



class Classifier: public drwnTMultiClassLogistic<drwnIdentityJointFeatureMap>
{
    public:
    vector< double > getWeights() {
        /*
        cout << "invoked" << endl;
        int nParameters = (*_weights).size();
        cout << "number of parameters: "<< nParameters << endl;
        vector< double > tempWeights(nParameters, 0.0);
        */
        vector< double > tempWeights(3, 0.0);
        for (int i = 0 ; i < 3; i ++ ) {
            tempWeights[i] =  _theta[i];
            //cout << _theta[i]  << endl;
        }
        return tempWeights;
    }

};
