###################################################
## FILENAME:    getFeatureMap.sh 
## AUTHOR:      Jimmy Lin (u5223173) 
## DATE:        2013-05-30
## DESCRIPTION: 
##     bash script to run the feature extraction
##     the image source is MSRA dataset B
##
###################################################
## Edited by MacVim
## Documentation autogenerated by snippet
###################################################

## input of this bash script: 
##    1. the mode 
##    2. the index of image package

## three modes: 
##    msc - multiscale contrast
##    csh - center surround histogram
##    csd - color spatial distribution

cp=$(pwd)

mode=$1
index=$2
outdir="../results/xxxxx"

cd $outdir && mkdir $index
cd $cp
if [[ $mode = "msc" || $mode = "csh" || $mode = "csd" ]] ; then
    ../../../bin/getFeatureMaps -x -verbose $mode "../dataset/images/B"/"$index"/ "$outdir"/"$index"
else 
    echo "Unrecognised mode. Please input one of msc, csh, or csd."
fi

