###################################################
## FILENAME:    getLabelledImage.sh
## AUTHOR:      Jimmy Lin (u5223173) 
## DATE:        2013-05-18
## DESCRIPTION: 
##     get images with labelled rectangles
##
###################################################
## Edited by MacVim
## Documentation autogenerated by snippet
###################################################


for x in $*
do  
    mkdir results/labels/
    mkdir results/labels/"$x"/
    ./../../bin/getLabelledImages -verbose -x dataset/images/B/$x dataset/labels/B/"$x"_data.txt results/labels/"$x"/
done
