###################################################
## FILENAME:    testTrainModel.sh
## AUTHOR:      Jimmy Lin (u5223173) 
## DATE:        2013-05-30
## DESCRIPTION: 
##     test the feature maps composed by 
##  multiscale contrast, center surround histogram,
##  Color spatial distribution
##
###################################################
## Edited by MacVim
## Documentation autogenerated by snippet
###################################################

## six argument for this program
##  const char *imgDir = DRWN_CMDLINE_ARGV[0]; // directory restores original images
##  const char *mscDir = DRWN_CMDLINE_ARGV[1]; // directory restores multiscale contrast feature map
##  const char *cshDir = DRWN_CMDLINE_ARGV[2]; // directory restores center surround histogram feature map
##  const char *csdDir = DRWN_CMDLINE_ARGV[3]; // directory restores color spatial distribution feature map
##  const char *lblFile = DRWN_CMDLINE_ARGV[4]; // a single text file with ground truth rectangle
##  const char *outputDir = DRWN_CMDLINE_ARGV[5]; // directory for resulting images

## 
for x in $*
do
    mkdir ./results/BComposed
    mkdir ./results/BComposed/$x
    ../../bin/trainModel -verbose -x ./dataset/images/B/$x/ ./results/BMultiscaleContrast/$x/ ./results/BCenterSurround/$x/ ./results/BColorSpatialDistribution/$x/ ./dataset/labels/B/"$x"_data.txt ./results/BComposed/$x/
done
